Brets work
christinaholt/csci3308_team2_finalproject pull request #4
Opened 2019-03-10 22:15 UTC by brmu4245

Okay, this is exciting! My first "pull request" with comment to boot!

There's a lot to unpack, but here's a brief summary:
1. Updated main script WorkoutScript_ds.py:
     a. reformatted with functions and loops, but keeping basic workings and format of output
     b. the output now prints to a document (workout_print.txt) that can temporarily store info for user and be read from
2. Created script_test.py:
     a. has 3 tests that checks for number of workouts generated and for varied workouts generated.
     b. still has a couple of bugs: last line shows no tests being run, and the first line always shows that too few arguments are being passed into the file.

2019-03-10 22:54 UTC, DRSessions commented
Looks good but I do have a few nitpicky things. 

First, does the main script "print" to a text file or does it write to the text file? Quickly scanning the code it looks like you have it formatted so the workout is assembled in a list and then that list is used to write to the text file but it doesn't look like the list or the text file are printed anywhere. I don't see any problem with this but I wanted to double check for clarity.

Another little thing is the comments on the commits. I personally like the dates like you have them but I can understand why that might not be ideal, I think the data is contained in the commits metadata. Some comments on commits aren't really that helpful, like simply saying a script was updated. Any commit is only going to create, delete or update something so the real info is in the details. The comments on the Pull Request are more like what I think the commit comments should be like -- they outline the updates instead of just stating that updates were made. But I could easily be wrong about the best practice for commenting on commits since I just started using Git.

2019-03-10 22:57 UTC, christinaholt requested changes
Bret, I left a few comments that I think we should probably address before turning in. I'd like to hear what everyone thinks, though!

2019-03-10 22:57 UTC, christinaholt commented on WorkoutScript_ds.py
> +csv_f = csv.reader(f)
We prob want to close this file. Maybe consider

```
with open('Exercises.csv', 'r') as fn:
    csv_f = csv.reader(fn)
```

2019-03-10 22:57 UTC, christinaholt commented on workout_print.txt
> +2 exercise(s) for arms randomly chosen):
I don't think we'll want to put this file in the repo since it's randomly generated output from a single instance of the script, and not reproducible.

2019-03-10 22:57 UTC, christinaholt commented on WorkoutScript_ds.py
> +    wkout_txt = open("workout_print.txt", "w")
Not sure we want to work with IO for this function, especially once we hook scripts together. Why not just return `Workout` and do the tests we need on that list?

2019-03-10 22:57 UTC, christinaholt commented on script_test.py
> +    WorkoutScript_ds.make_workout(1,0,0,0,0)
If we don't do the I/O bit, then this logic would collapse to:

```
workout_list = WorkoutScript_ds.make_workout(1,0,0,0,0)
assert(len(workout_list) == 1)
```

This means we don't have to worry too much about the last line being a blank line, or not, etc.

2019-03-10 22:57 UTC, christinaholt commented on script_test.py
> +
Again, this could become:

```
workout = WorkoutScript_ds.start_wkout("short")
assert(len(workout) == 6)
```

We might also want to assert something about the types of workouts we get in there? No?

2019-03-10 22:57 UTC, christinaholt commented on script_test.py
> +
Maybe something like above here, too?

```
workout1 =  WorkoutScript_ds.start_wkout("medium")
workout2 =  WorkoutScript_ds.start_wkout("medium")
assert(workout1 != workout2)
```
This one may require that we sort the list we get back...not entirely sure if order matters in a compare of lists.

2019-03-10 23:09 UTC, DRSessions commented on WorkoutScript_ds.py
> +    wkout_txt = open("workout_print.txt", "w")
I was wondering this too. The two structures made in this function are the list and the file and I can see a few benefits to working with either, is there any downside to returning a specific data structure like a list instead of something more general like a text file? The downside for text file is that you need to write to it at one stage then read from it at another.

2019-03-10 23:17 UTC, DRSessions commented on script_test.py
> +
I think it would depend on if our workout is intended to be a specific sequence of exercises or just a collection of exercises. If it's a sequence, then a workout that has squats THEN sit-ups would be different than one that has sit-ups THEN squats. The order would matter and (squats, sit-ups) != (sit-ups, squats). But if we are giving a collection of exercises that says to do squats and sit-ups at some point in the workout, order wouldn't matter a list like (squats, sit-ups) == (sit-ups, squats).

As far as I know we are just providing a collection of workouts to be completed without a specific order, although it would be reasonable to do if we anted to.

2019-03-10 23:18 UTC, DRSessions commented on workout_print.txt
> +2 exercise(s) for arms randomly chosen):
Agreed. As it's written now, the file will be generated locally and wouldn't need to be provided in the repo.

2019-03-10 23:24 UTC, brmu4245 commented on WorkoutScript_ds.py
> +csv_f = csv.reader(f)
Yes! We should close it!

2019-03-10 23:26 UTC, brmu4245 commented on workout_print.txt
> +2 exercise(s) for arms randomly chosen):
I'm a little confused as to why there's a + symbol above in your example...

This was the original statement from the script. I was trying to keep the integrity of what Derek and Lauren produced since that was not my responsibility to change. We don't have to have that statement in there, it was there before I worked with it.

2019-03-10 23:30 UTC, brmu4245 commented on WorkoutScript_ds.py
> +    wkout_txt = open("workout_print.txt", "w")
Maybe it was my method, but I tried working with the output of Workout, but my tests would return nothing.

I spent a couple of hours trying to get the information directly from Workout, but my code couldn't work with it. This was an idea I had since I thought it would be useful to store the last workout created. I figured writing an html file to read a text would be easier than a direct link. I could be wrong.

2019-03-10 23:32 UTC, brmu4245 commented on script_test.py
> +    WorkoutScript_ds.make_workout(1,0,0,0,0)
Correct. Again, I was trying to keep what Derek and Lauren had with the original line introducing the type of workout being done. In this case, an extra line would have to be added to keep that output. If we decide as a group to keep it, great! If not, then I'll adjust the tests to reflect that.

2019-03-10 23:34 UTC, brmu4245 commented on script_test.py
> +
Yes, there are more tests we could run. I was trying to get the minimum completed and thought I'd wait on the added features before I wrote more. If everyone thinks I should go ahead and create more tests, I could do that.

2019-03-10 23:35 UTC, brmu4245 commented
Alright! Great feedback. A lot to go through. I have answers for some, and others are good points.

Derek:
1. Yes, it is writing to a file. The file is created if it isn't already. The file holds the last run of the program. It then re-writes over it the next time the program is run. If you perform an "ls" on the command line, you should see the file "workout_print.txt" there.
2. As far as my commits,.. They're a work in progress. Those are remnants of my learning to do commits and performing them from the command line. I apologize for any confusion about that. I feel like over the last 24 hours, I've gotten better. I will take your suggestions to heart as I continue to learn.

Christina:
I've replied to your comments individually.

2019-03-10 23:36 UTC, brmu4245 commented on WorkoutScript_ds.py
> +csv_f = csv.reader(f)
There is a method that Thomas mentioned that doesn't require a specific line for closing. I tried to find it, but thought we could ask him too.

2019-03-10 23:47 UTC, DRSessions commented on WorkoutScript_ds.py
> +csv_f = csv.reader(f)
I believe the line you are looking for is the one that Christina provided. When used like she has it, the file automatically closes after executing the indented block of code after it opens.

2019-03-10 23:50 UTC, brmu4245 commented on workout_print.txt
> +2 exercise(s) for arms randomly chosen):
Ah, okay. I understand. We can definitely delete the file. As the program is run, it will be continually generated. Leaving it in could be an artifact to show as an example.

2019-03-11 00:05 UTC, DRSessions commented on workout_print.txt
> +2 exercise(s) for arms randomly chosen):
I believe the '+' symbol is result of something like "git diff" and actually shows the lines that you edited and are requesting to pull to master, which is why you recognize it as the original statement in the script. All of Christina's comments are 'requests for changes' but I don't think she has the ability to make those changes herself so all of the code is what you provided.
I assume that she put her comment on the first line of the file for convenience but it's not actually about that line of code, but the entire workout_print.txt file. 

Her point is that in WorkoutScript_ds.py, the code will CREATE the file workout_print.txt and because it is randomly generated it won't look like the workout_print.txt file that is currently in the repo. The file in the repo is one specific result of running the script and making a workout but we don't need to put that in the repo. We just need the script and it will produce a fresh file when it's ran.

Edit: Looks like you understand what she meant now but I'll leave my comment in case it's helpful at all

2019-03-11 00:20 UTC, brmu4245 commented on workout_print.txt
> +2 exercise(s) for arms randomly chosen):
Please, all this information and feedback is great! Sometimes I understand things differently (and in some cases as today, incorrectly). It can be beneficial, but can also make things confusing. I am trying to respondly in a timely manner so that we can make corrections as necessary. I still have some things to learn about using Github, git, and how to work in an environment like this. I worry about not helping enough and then help too much.

2019-03-11 05:47 UTC, christinaholt commented on WorkoutScript_ds.py
> +    return wkout_txt
So, you mentioned in another comment that you couldn't get the original code to work with a list like you wanted. It seems that maybe since it was printing all it's output instead of returning it (like you've done here with the open text file), you could have had some troubles related to that. Maybe a `return Workout` would get you the testable list you were looking for.

2019-03-11 17:31 UTC, laurenedeans commented on WorkoutScript_ds.py
> +    wkout_txt = open("workout_print.txt", "w")
So as this is right now, it is writing the generated workout to a text file? What will be the easiest way to use it with html?

2019-03-11 17:36 UTC, laurenedeans commented on workout_print.txt
> +	Diamond Push-Ups -- Arms (Triceps, Deltoids, Chest)  -- Body Weight, Resistance Training
Arm exercise generated in leg category.. logic issue

2019-03-11 17:36 UTC, laurenedeans commented on workout_print.txt
> +	Stairmaster -- Legs (Quadriceps, Glutes, Hamstrings)  -- Machine, Cardio
leg in back

2019-03-11 18:12 UTC, laurenedeans commented on script_test.py
Is the purpose of printing "Workout List 1" and "Workout List 2" to show the comparison? If so, I think testing it is good enough, if it passes or fails you know the exercises are either the same or different. Also at this point with our small database it might hurt us more than help us to be testing for identical exercises since we know they happen frequently? 

How about testing for correct muscle group, aka arm exercises in arm workout, etc.

just suggestions! I appreciate your hard work.

2019-03-12 04:47 UTC, christinaholt approved these changes

2019-03-12 04:47 UTC, christinaholt commented on WorkoutScript_ds.py
> +    return make_workout(*predefined_set)
The test case works if the list is returned, so doing that here. I also needed to change the numbers to coincide with the numbers of exercises we have in the CSV file for each focus area. Once we get those numbers up, we can go back to the magic recipe if needed.

2019-03-12 04:47 UTC, christinaholt commented on WorkoutScript_ds.py
> +        Workout.extend(sample)
The random.sample here ensures that we get n different exercises, instead of leaving it to chance that we could get duplicates.

2019-03-12 04:47 UTC, christinaholt commented on WorkoutScript_ds.py
> +    return Workout
The behavior of the script is now back to printing out a workout to the screen. No text files are written.

2019-03-12 05:01 UTC, merged